apiVersion: v1
kind: Service
metadata:
  name: akka-cells
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    run: akka-cells
  clusterIP: None
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    run: akka-cells
  name: akka-cells
spec:
  serviceName: akka-cells
  replicas: 1
  selector:
    matchLabels:
      run: akka-cells
  template:
    metadata:
      labels:
        run: akka-cells
    spec:
      containers:
      - name: akka-cells
        image: capdev12/cell
        env:
        - name: ROLES
          value: genRole
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
#        - name: BIND_HOST_NAME
#          valueFrom:
#            fieldRef:
#              apiVersion: v1
#              fieldPath: status.podIP
        - name: SEED_NODES
          value: akka-cells-0.akka-cells,akka-cells-1.akka-cells
        command: ["/bin/sh", "-c", "HOST_NAME=${POD_NAME}.akka-cells java -jar /home/Cell/Cell.jar"]
        livenessProbe:
          tcpSocket:
            port: 8090
        ports:
        - containerPort: 8090
          protocol: TCP

